# Generated by Django 3.2 on 2022-11-15 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20221115_0850'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='favorite',
            name='favorite',
        ),
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='favorited'),
        ),
    ]
